#!/usr/bin/env python3
# BifrAuth: Unicode 16.0 の General_Category=Cn（未割当＋非文字）レンジ表を生成する。
#
# 使い方（再現手順）:
#   curl -fsSL https://www.unicode.org/Public/16.0.0/ucd/extracted/DerivedGeneralCategory.txt \
#     -o DerivedGeneralCategory-16.0.txt
#   python3 tools/unicode/gen_cn_table.py DerivedGeneralCategory-16.0.txt \
#     > crates/bifrauth-proto/src/unicode_cn.rs
#
# 生成物は @generated で手編集禁止。Unicode バージョン・生成元 URL・入力の SHA-256 を
# ファイル先頭に埋め込み、ビルド時のネットワーク取得はしない（vendored）。
# 出力は Rust/Swift で同一集合を共有するための一次データ。

import hashlib
import sys

SOURCE_URL = "https://www.unicode.org/Public/16.0.0/ucd/extracted/DerivedGeneralCategory.txt"
UNICODE_VERSION = "16.0.0"
# 入力を機械的に固定する。別バージョン（例 Unicode 17.0）を渡しても 16.0 として生成しないよう、
# 生の SHA-256 とヘッダの版を検査し、不一致なら生成を拒否する。
EXPECTED_SHA256 = "7676ab755a41ef82108460238569e60ad65c191ddafe61b36c6765ec1353f293"


def parse_cn_ranges(text):
    ranges = []
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        rng, cat = [x.strip() for x in line.split(";")]
        if cat != "Cn":
            continue
        if ".." in rng:
            a, b = rng.split("..")
            a, b = int(a, 16), int(b, 16)
        else:
            a = b = int(rng, 16)
        ranges.append((a, b))
    ranges.sort()
    # 隣接（end+1 == 次の start）を結合してコンパクト化する。
    merged = []
    for a, b in ranges:
        if merged and a <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], b))
        else:
            merged.append((a, b))
    return merged


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen_cn_table.py <DerivedGeneralCategory.txt>")
    raw = open(sys.argv[1], "rb").read()
    sha = hashlib.sha256(raw).hexdigest()
    if sha != EXPECTED_SHA256:
        sys.exit(
            f"error: input SHA-256 {sha} != expected {EXPECTED_SHA256}.\n"
            f"       expected the Unicode {UNICODE_VERSION} file from {SOURCE_URL}.\n"
            "       別バージョンのUCDからは生成しない（wireをUnicode 16.0に固定するため）。"
        )
    text = raw.decode("utf-8")
    if f"DerivedGeneralCategory-{UNICODE_VERSION}" not in text.splitlines()[0]:
        sys.exit(f"error: 入力ヘッダに DerivedGeneralCategory-{UNICODE_VERSION} が無い")
    ranges = parse_cn_ranges(text)
    total = sum(b - a + 1 for a, b in ranges)

    out = []
    out.append("// @generated by tools/unicode/gen_cn_table.py — DO NOT EDIT.")
    out.append(f"// Source: {SOURCE_URL}")
    out.append(f"// Unicode version: {UNICODE_VERSION}")
    out.append(f"// Source SHA-256: {sha}")
    out.append(f"// Ranges: {len(ranges)}  (code points: {total})")
    out.append("//! Unicode 16.0 の `General_Category=Cn`（未割当＋非文字）レンジ表（vendored）。")
    out.append("//!")
    out.append("//! wire を Unicode 16.0 に固定するため、未割当判定はライブラリのカテゴリ表ではなく")
    out.append("//! この表で行う（Rust/Swift 共有）。詳細は `spec/cbor-profile.md` §7.1。")
    out.append("")
    out.append("/// (start, end) 昇順・非重複の inclusive レンジ。")
    out.append("pub(crate) const CN_RANGES: &[(u32, u32)] = &[")
    for a, b in ranges:
        out.append(f"    (0x{a:04X}, 0x{b:04X}),")
    out.append("];")
    out.append("")
    out.append("/// `cp` が Unicode 16.0 で Cn（未割当＋非文字）かを binary search で判定する。")
    out.append("pub(crate) fn is_cn(cp: u32) -> bool {")
    out.append("    CN_RANGES")
    out.append("        .binary_search_by(|&(lo, hi)| {")
    out.append("            if cp < lo {")
    out.append("                core::cmp::Ordering::Greater")
    out.append("            } else if cp > hi {")
    out.append("                core::cmp::Ordering::Less")
    out.append("            } else {")
    out.append("                core::cmp::Ordering::Equal")
    out.append("            }")
    out.append("        })")
    out.append("        .is_ok()")
    out.append("}")
    out.append("")
    out.append("#[cfg(test)]")
    out.append("mod tests {")
    out.append("    use super::is_cn;")
    out.append("")
    out.append("    #[test]")
    out.append("    fn known_reserved_and_noncharacters_are_cn() {")
    out.append("        assert!(is_cn(0x0378)); // reserved")
    out.append("        assert!(is_cn(0xFDD0)); // noncharacter")
    out.append("        assert!(is_cn(0xFFFE)); // noncharacter")
    out.append("        assert!(is_cn(0x10FFFF)); // noncharacter")
    out.append("        assert!(is_cn(0x088F)); // 16.0 では reserved（17.0 で割当）")
    out.append("    }")
    out.append("")
    out.append("    #[test]")
    out.append("    fn known_assigned_are_not_cn() {")
    out.append("        assert!(!is_cn(0x0041)); // 'A'")
    out.append("        assert!(!is_cn(0x3042)); // 'あ'")
    out.append("        assert!(!is_cn(0x1F600)); // 😀")
    out.append("    }")
    out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
