#!/usr/bin/env python3
# BifrAuth: generate the Unicode 16.0 General_Category=Cn (unassigned + noncharacter) range table.
#
# Usage (reproduction steps):
#   curl -fsSL https://www.unicode.org/Public/16.0.0/ucd/extracted/DerivedGeneralCategory.txt \
#     -o DerivedGeneralCategory-16.0.txt
#   python3 tools/unicode/gen_cn_table.py DerivedGeneralCategory-16.0.txt \
#     > crates/bifrauth-proto/src/unicode_cn.rs
#
# The output is @generated (do not edit by hand). It embeds the Unicode version, source URL, and the
# input SHA-256 at the top, and requires no network access at build time (vendored).
# The output is primary data for sharing the same set between the Rust and Swift implementations.

import hashlib
import sys

SOURCE_URL = "https://www.unicode.org/Public/16.0.0/ucd/extracted/DerivedGeneralCategory.txt"
UNICODE_VERSION = "16.0.0"
# Fix the input mechanically. To avoid generating from a different version (e.g. Unicode 17.0) as if
# it were 16.0, verify the raw SHA-256 and the header version, and refuse to generate on mismatch.
EXPECTED_SHA256 = "7676ab755a41ef82108460238569e60ad65c191ddafe61b36c6765ec1353f293"


def parse_cn_ranges(text):
    ranges = []
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        rng, cat = [x.strip() for x in line.split(";")]
        if cat != "Cn":
            continue
        if ".." in rng:
            a, b = rng.split("..")
            a, b = int(a, 16), int(b, 16)
        else:
            a = b = int(rng, 16)
        ranges.append((a, b))
    ranges.sort()
    # Merge adjacent ranges (end+1 == next start) to compact the table.
    merged = []
    for a, b in ranges:
        if merged and a <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], b))
        else:
            merged.append((a, b))
    return merged


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen_cn_table.py <DerivedGeneralCategory.txt>")
    raw = open(sys.argv[1], "rb").read()
    sha = hashlib.sha256(raw).hexdigest()
    if sha != EXPECTED_SHA256:
        sys.exit(
            f"error: input SHA-256 {sha} != expected {EXPECTED_SHA256}.\n"
            f"       expected the Unicode {UNICODE_VERSION} file from {SOURCE_URL}.\n"
            "       Do not generate from a different UCD version (the wire is pinned to Unicode 16.0)."
        )
    text = raw.decode("utf-8")
    if f"DerivedGeneralCategory-{UNICODE_VERSION}" not in text.splitlines()[0]:
        sys.exit(f"error: input header does not contain DerivedGeneralCategory-{UNICODE_VERSION}")
    ranges = parse_cn_ranges(text)
    total = sum(b - a + 1 for a, b in ranges)

    out = []
    out.append("// @generated by tools/unicode/gen_cn_table.py — DO NOT EDIT.")
    out.append(f"// Source: {SOURCE_URL}")
    out.append(f"// Unicode version: {UNICODE_VERSION}")
    out.append(f"// Source SHA-256: {sha}")
    out.append(f"// Ranges: {len(ranges)}  (code points: {total})")
    out.append("//! Unicode 16.0 `General_Category=Cn` (unassigned + noncharacter) range table (vendored).")
    out.append("//!")
    out.append("//! To pin the wire to Unicode 16.0, the unassigned check uses this table rather than a")
    out.append("//! library's category table (shared by Rust/Swift). See `spec/cbor-profile.md` §7.1.")
    out.append("")
    out.append("/// (start, end) inclusive ranges, ascending and non-overlapping.")
    out.append("pub(crate) const CN_RANGES: &[(u32, u32)] = &[")
    for a, b in ranges:
        out.append(f"    (0x{a:04X}, 0x{b:04X}),")
    out.append("];")
    out.append("")
    out.append("/// Returns whether `cp` is Cn (unassigned + noncharacter) in Unicode 16.0, via binary search.")
    out.append("pub(crate) fn is_cn(cp: u32) -> bool {")
    out.append("    CN_RANGES")
    out.append("        .binary_search_by(|&(lo, hi)| {")
    out.append("            if cp < lo {")
    out.append("                core::cmp::Ordering::Greater")
    out.append("            } else if cp > hi {")
    out.append("                core::cmp::Ordering::Less")
    out.append("            } else {")
    out.append("                core::cmp::Ordering::Equal")
    out.append("            }")
    out.append("        })")
    out.append("        .is_ok()")
    out.append("}")
    out.append("")
    out.append("#[cfg(test)]")
    out.append("mod tests {")
    out.append("    use super::is_cn;")
    out.append("")
    out.append("    #[test]")
    out.append("    fn known_reserved_and_noncharacters_are_cn() {")
    out.append("        assert!(is_cn(0x0378)); // reserved")
    out.append("        assert!(is_cn(0xFDD0)); // noncharacter")
    out.append("        assert!(is_cn(0xFFFE)); // noncharacter")
    out.append("        assert!(is_cn(0x10FFFF)); // noncharacter")
    out.append("        assert!(is_cn(0x088F)); // reserved in 16.0 (assigned in 17.0)")
    out.append("    }")
    out.append("")
    out.append("    #[test]")
    out.append("    fn known_assigned_are_not_cn() {")
    out.append("        assert!(!is_cn(0x0041)); // 'A'")
    out.append("        assert!(!is_cn(0x3042)); // Hiragana 'a'")
    out.append("        assert!(!is_cn(0x1F600)); // grinning face emoji")
    out.append("    }")
    out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
